using System;

namespace Aion.Domain.Security
{
    /// <summary>
    /// Represents an application user.  Users are stored in the S_User table and
    /// are linked to groups via the S_Groupe_User table.  Each user belongs to a
    /// tenant and is identified by a GUID.
    /// </summary>
    public sealed class UserEntity
    {
        /// <summary>
        /// Primary key.  This value is generated by the application when creating
        /// new users.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Identifier of the tenant to which this user belongs.  Use
        /// <see cref="Guid.Empty"/> for the default/global tenant.
        /// </summary>
        public Guid TenantId { get; set; }

        /// <summary>
        /// Login name for authentication.  Should be unique per tenant.
        /// </summary>
        public string Login { get; set; } = string.Empty;

        /// <summary>
        /// SHA‑256 hash of the user's password in hexadecimal format.  Do not
        /// store plain text passwords.  When validating a login, compute the
        /// SHA‑256 hash of the provided password and compare it to this value.
        /// </summary>
        public string PasswordHash { get; set; } = string.Empty;

        /// <summary>
        /// Display name of the user.  This value is used in the UI when showing
        /// the current user's name.
        /// </summary>
        public string Name { get; set; } = string.Empty;
    }
}