using Aion.DataEngine.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Aion.Infrastructure.Configurations.Common;

public abstract class BaseEntityConfiguration<TEntity> : IEntityTypeConfiguration<TEntity> where TEntity : BaseEntity
{
    public void Configure(EntityTypeBuilder<TEntity> builder)
    {
        builder.HasKey(x => x.Id);

        // Align BaseEntity mappings with the legacy SQL schema generated by the provisioning service.
        builder.Property(x => x.Id).UseIdentityColumn();
        builder.Property(x => x.TenantId).HasDefaultValue(1);
        builder.Property(x => x.Actif).HasDefaultValue(true);
        builder.Property(x => x.Doc).HasDefaultValue(false);
        builder.Property(x => x.Deleted).HasDefaultValue(false);
        builder.Property(x => x.DtCreation).HasDefaultValueSql("GETUTCDATE()");
        builder.Property(x => x.DtModification).HasDefaultValueSql("GETUTCDATE()");
        builder.Property(x => x.RowVersion).IsRowVersion();

        ConfigureEntity(builder);
    }

    protected abstract void ConfigureEntity(EntityTypeBuilder<TEntity> builder);
}
